// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WordsEater.Models;

[Index("Id", IsUnique = true)]
[Index("Word", IsUnique = true)]
public partial class StudyLog
{
    [Key]
    public long Id { get; set; }

    [Required]
    public string Word { get; set; }

    public long? RightOrWrong { get; set; }

    public string Time { get; set; }
}