// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WordsEater.Models;

[Index("Id", IsUnique = true)]
[Index("word", IsUnique = true)]
public partial class Words
{
    [Key]
    public long Id { get; set; }

    [Required]
    public string word { get; set; }

    public string ChineseInterpretation { get; set; }

    public string EnglishInterpretation { get; set; }

    public string Examples { get; set; }

    public long? TotalStudiedTimes { get; set; }

    public long? TotalWrongTimes { get; set; }
}